name: Build Dockerfile With Latest Tag

on:
  push:
    branches:
      - main

jobs:
  build-latest:
    runs-on: ubuntu-latest
    steps:
      - run: env
      - run: curl ${{ dockerhub.WEBHOOK_BUILD_LATEST }}
